### ISSUE TITLE
AESUnwrap: integrity check FAIL error on macOs 10.14 

### ISSUE THREAD

**Issue by harish1094** [n0fate/iChainbreaker#5]
On latest MacOs version 10.14 I received  following error while running  
$ iChainbreaker.py  -p /Users/ssk/Library/Keychains/524D25E7-7C27-5FC0-XXXX-DBCF5BC6101E/ -k password -v 10.14

Error :- 
Tool for iCloud Keychain Analysis by @n0fate
[*] macOS version is 10.14
[*] UUID : 524D25E7-7C27-5FC0-XXXX-DBCF5BC6101E
[*] Keybag : /Users/ssk/Library/Keychains/524D25E7-7C27-5FC0-XXXX-DBCF5BC6101E/user.kb
[*] iCloud Keychain File : /Users/ssk/Library/Keychains/524D25E7-7C27-5FC0-XXXX-DBCF5BC6101E/keychain-2.db
[+] Keybag Header
 [-] versions : 5
 [-] type : System Keybag
 [-] uuid : ef0bd07c-a810-4463-XXXX-a740916acf21
 [-] hmac key : 8e0022157161caedf64d64c5915013a1531debf4ce0f5998ddd71ce9740763a1442dcd85f1e17a21
 [-] wrap : None
 [-] salt : 4f9c4d7acbfa5d2b322df923149de87e43efb0f8
 [-] iteration count : 100000
 [-] Signature : 9252299d6a3ae69ae465d3d62af5d77ba50ed227
[*] The Device key : f48eb94f96818d164ce992e998e5cdccbcb4569551b9284bc95d56b6c7b694be
[*] Device Key validation : Pass
[*] The passcode key : 9d744b8d9220b146dedf64801b6b639854484878e3b940473798d4b27911b663
Traceback (most recent call last):
  File "iChainbreaker.py", line 220, in <module>
    main()
  File "iChainbreaker.py", line 133, in main
    keybag.Decryption()
  File "/Users/ssk/Downloads/iChainbreaker-master-2/keybag.py", line 180, in Decryption
    unwrapped = AESUnwrap(self.passcodekey, data)
  File "/Users/ssk/Downloads/iChainbreaker-master-2/crypto/aeswrap.py", line 33, in AESUnwrap
    assert A == 0xa6a6a6a6a6a6a6a6, "AESUnwrap: integrity check FAIL, wrong kek ? %x"%A
AssertionError: AESUnwrap: integrity check FAIL, wrong kek ? 1dbc0b68e8b3fe39

Thanks..

**Comment by LukeHandle** [comment]
Same issue 😬 Did you get a resolution @harish1094 ? Also would avoid putting anything "key" related on GH ^^
