### ISSUE TITLE
AESUnwrap fails in 10.15 Catalina

### ISSUE THREAD

**Issue by anonymouz4** [n0fate/iChainbreaker#9]
Same as #5, just for 10.15 this time.

```
[*] macOS version is 10.15
[*] Keybag Header
 [*] versions : 4
 [*] type : System Keybag
 [*] wrap : Wrapped key after AES encrypted with device key
 [*] iteration count : 50000

assert A == 0xa6a6a6a6a6a6a6a6, "AESUnwrap: integrity check FAIL, wrong kek ? %x"%A
AssertionError: AESUnwrap: integrity check FAIL, wrong kek ? a0e23b64db0c.... 
```

DeviceKey Validation fails at `AESUnwrap`, even before comparing to `sign`.

Since the DeviceKey seems to be fine, I guess, the unwrapping changed 
(`AppleKeyStore.kext -> AppleKeyStore::device_key_init()` code stayed the same)

```
rax = _uuid_parse(rax, &var_30);
if (rax == 0x0) {
    ccpbkdf2_hmac(_ccsha256_di(), 0x10, &var_30, 0x0, 0x0, 0xc350, 0x20, r14 + 0x118);
    *(int8_t *)AppleKeyStore::device_key_init()::device_key_initialized = 0x1;
}
```

**Comment by n0fate** [comment]
If your mac has T1/T2 chipset, this error can be occured. I think t1/t2 weighed in with key generation.

**Comment by anonymouz4** [comment]
Yes, I've got the T1 Chip, but still, the device key must be generated somehow. Any idea where the issue could be?

**Comment by n0fate** [comment]
Yes. Anybody can not solve this problem. iChainbreaker worked well when I tested against Mojave on macOS without T1/2 chip.

**Comment by n0fate** [comment]
But macOS with T1/2 chip, it doesn't worked.
